config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  resources :relationships, only: [:create, :destroy]
  resources :pictures do
    resources :comments
    collection do
      patch :confirm
      post :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :conversations do
    resources :messages
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_secure_password

  before_validation { email.downcase! }

  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
    <li><%= render 'follow_form', user: user %></li> <!-- フォロー機能が実装されて入ればこの一文も必要 -->
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

<%= link_to '一覧に戻る', pictures_path %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<div class="following_user">
  <h2>フォローしている人</h2>
  <% @user.following.each do |user| %>
    <p><%= user.name  %> </p>
  <% end %>
</div>

<div class="folloed_user">
  <h2>フォローしてくれてる人</h2>
  <% @user.followers.each do |user| %>
    <p><%= user.name  %> </p>
  <% end %>
</div>


  <%= link_to '記事一覧', pictures_path %>