config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  resources :relationships, only: [:create, :destroy]
  resources :pictures do
    resources :comments
    collection do
      patch :confirm
      post :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :conversations do
    resources :messages
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :test]
  before_action :test, only: [:edit, :destroy, :update]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all.includes(:user)
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @comments = @picture.comments
    @comment = @picture.comments.build
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new and return
    end
    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    if params[:back]
      @picture = Picture.new(picture_params)
      render :edit
    else
      respond_to do |format|
        if @picture.update(picture_params)
          format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
          format.json { render :show, status: :ok, location: @picture }
        else
          format.html { render :edit }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    @picture.id = params[:id]
    render :new if @picture.invalid?
  end

  def test
    if current_user.id != @picture.user_id
      redirect_to pictures_path, notice: "権限がありません"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:id, :title, :content, :user_id, :image, :image_cache)
    end
  end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm" || action_name == "create"
      confirm_pictures_path
    elsif action_name == "edit"
      confirm_picture_path
    end
  end

  def confirm_new_or_edit
    unless @picture.id?
      pictures_path
    else
      picture_path
    end

  end

  def confirm_form_method
    @picture.id ? 'patch' : 'post'
    # if @blog.id.nil?
    #   puts "oooooooooooooooooooo"
    #   "patch"
    # else
    #   puts "nnnnnnnnnnnnnnnnn"
    #   "post"
    # end
  end
end

app/views/pictures/_form.html.erb
<%= form_with(model: picture, url: choose_new_or_edit, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form. label :content%>
    <%= form.text_area :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: confirm_new_or_edit,  method: confirm_form_method,  local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>


  <p>タイトル:<%= @picture.title %></p>
  <p>本文:<%= @picture.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>一覧</h1>

<table class="">


  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <% if picture.image.url.present? %>
        <td><%= image_tag picture.image.url %></td> 
        <% end %>
        <td><%= picture.content %></td>
        <td><%= picture.user.name %></td>
        <% if logged_in? %>
           <% if current_user.id == picture.user.id %>
            <td><%= link_to 'Show', picture %></td>
            <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
            <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        <td class="layoutBlock"></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @picture.user.name %>
</p>
<% if @picture.image.url.present? %>
<p>
  <strong>Image:</strong>

  <%= image_tag @picture.image.url %>
</p>

<% end %>

<div id="comments_area">
  <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'comments/index', locals: { comments: @comments, picture: @picture } %>
</div>

<!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
<%= render partial: 'comments/form', locals: { comment: @comment, picture: @picture } %>

</div>

<%= link_to 'Edit', edit_picture_path(@picture) %>
<%= link_to 'Back', pictures_path %>