config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  resources :relationships, only: [:create, :destroy]
  resources :pictures do
    resources :comments
    collection do
      patch :confirm
      post :confirm
    end
    member do
      patch :confirm
    end
  end
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :conversations do
    resources :messages
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFacebook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="header container-fluid">
    <h2 class="">Facebook</h2>
    <div class="nav">

  </header>
  <div class="wrap container">
    <% if logged_in? %>
      <%= link_to "マイページ", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "会員登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
      <p><%= link_to 'ユーザー一覧', users_path if logged_in? %></p>

    
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <% if logged_in? %>
    <%= link_to 'New Picture', new_picture_path %>
  <% end %>

  <%= yield %>
</div>
<footer>
  
</footer>

</body>
</html>